globalvar dir;
dir = 1;
globalvar catsw1;
catsw1 = false;
globalvar catsw2;
catsw2 = false;
globalvar catsw3;
catsw3 = false;
globalvar catsw4;
catsw4 = false;
globalvar swCat;
swCat = false;
globalvar catNum;
catNum = 0;
globalvar swCat2;
swCat2 = false;
globalvar catspr;
catspr = false;